Newarticle
OpenScienceLabs/articles pull request #4
Opened 2022-01-25 16:56 UTC by EverVino

Articulo en "data viz" para mapas en R 
@xmnlab @eunrod16

2022-01-29 18:03 UTC, xmnlab requested changes
@EverVino, muchas gracias por enviar este artículo.

He dejado algunos comentarios en sus líneas respectivas.

Resumen de la revisión de markdown:

- triple backtick (``` ` ```) se usa para multilínea, y no para un texto en la misma línea, excepto si lo necesitas para escapar un backtick en el texto 
- antes y después de un bloque con triple backtick, hay que tener una línea en blanco
- antes y después de títulos, imágenes y listas dejar una línea en blanco
- usar backtick ``` ` ``` para nombres de variables, funciones, bibliotecas etc.
- especificar bloques de código `r` para los códigos `r`. Ejemplo: ```` ```r ``` ````
- para resaltar una palabra, usar negrita, y no comillas

Resumen de la revisión de texto:

- usar **biblioteca** en lugar de **librería**
- no repetir mucho una misma palabra y sus variantes en el mismo párrafo. Por ejemplo, has usado mucho la palabra `asignar` y sus variantes. Por favor, revisar otra vez el texto y reducir las repeticiones.
-  no usar emojis
- usar comas para separar las sentencias
- no tener muchas sentencias en la misma frase. romper en más frases y cada sentencia tiene que estar conectada de manera fluída
- usar más los artículos antes de los sustantivos
- hubo muchas palabras que faltaban tildes o estaban en sílabas equivocadas
- hubo algunos errores ortográficos

Tips generales:

- usar corrector ortográfico para chequear el texto
- para auto-formatear códigos R, puedes usar alguna lib, por ejemplo: https://stackoverflow.com/a/34856235
- para el próximo artículo, sería mejor usar jupyter-notebook. Incluso puedo crear una estructura para que el lector/a pueda ejecutar tus código en mybinder o google collab (espero pronto tener esto listo)


PS: voy a escribir una guia para los artículos que espero les ayude para sus próximo PRs.

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +_Este breve tutorial te mostrará como graficar los mapas y modificar sus atributos. Al finalizar el tutorial podrás crear un mapa de densidad poblacional como el mostrado a continuación._
```suggestion
Este breve tutorial te mostrará como graficar los mapas y modificar sus atributos. Al finalizar el tutorial podrás crear un mapa de densidad poblacional como el mostrado a continuación.
```

la marcación usada con `_` del primer párrafo específico no se va a ver bien en la página index (hecha por un script)

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +
sería bueno que entre la línea 1 y 3 haya una imagen para tu artículo, ella estará presente en la página inicial.

para ello tienes que subir una imagen llamada `header.png` en la carpeta de tu artículo.

aquí puedes encontrar algunas opciones para eligir la imagen de portada de tu artículo:

1) https://www.glazestock.com/
2) https://drawkit.com/
3) https://undraw.co/illustrations

me avisas si tienes cualquier duda

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +![alt text](grafica2.png)
en lugar de "alt texto", mejor dejar un texto descriptivo sobre la imagen

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +Explicando que contiene un fichero formato Shapefile.
```suggestion
Para este artículo vamos a utilizar archivos de formato Shapefile. Si todavía no sabes de qué se trata, te explicamos a continuación.

```

arriba te dejo un ejemplo introduciendo un poco el porqué vas a decir sobre shapefile

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +* .dbf - un archivo tipo attibute, tiene los atributos de cada forma en una columna es de tipo dBase IV.
```suggestion
* .dbf - un archivo tipo attribute, tiene los atributos de cada forma en una columna, es de tipo dBase IV.
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +Adicionalmente la carpeta donde se encuentran dichos archivos pueden contener otros archivos de formato .prj o .sbn que aportan más datos de la geometria, o que pueden ser usados en otros programas d
```suggestion
Adicionalmente la carpeta donde se encuentran dichos archivos pueden contener otros archivos de formato .prj o .sbn que aportan más datos de la geometria, o que pueden ser usados en otros programas de sistemas de información geográfico.
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +La librería que nos ayudara a importar este tipo de archivos es ```rgdal```, y la librería que convertira los archivos importados en una tabla de datos es ```broom``` (los datos que nos interesan den
```suggestion
La librería que nos ayudará a importar este tipo de archivos es ```rgdal```, y la librería que convertirá los archivos importados en una tabla de datos es ```broom``` (los datos que nos interesan dentro las tablas son latitud y longitud en formato decimal que son coordenadas geográficas de nuestro planeta, estas se convierten a nuestros datos `x` e `y` para nuestro gráfico) al tenerla en una tabla podemos usar la opción de graficarla como polígonos usando ```ggplot2```.
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +#### Donde conseguir los archivos shapefile
```suggestion
### ¿Dónde conseguir los archivos shapefile?
```

el alterior encabezado era de nivel 2 .. así que este tiene que ser de nivel 3

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +Muchos de estos archivos Shapefile representan mapas de nuestros Estados, por lo que estan disponibles de manera gratuita en la mayoria de los casos. Otros son de paga y están más completos y/o actua
```suggestion
Muchos de estos archivos Shapefile representan mapas de nuestros Estados, por lo que estan disponibles de manera gratuita en la mayoria de los casos. Otros son de paga y están más completos y/o actualizados y/o poseen datos específicos. A continuación, algunos web que ofrecen mapas:
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +[data.humdata.org](https://data.humdata.org/) Para shapefiles varios países del mundo. (Algunos están desactualizados)
```suggestion
- [data.humdata.org](https://data.humdata.org/) Para shapefiles de varios países del mundo. (Algunos están desactualizados)
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +
```suggestion
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +[geo.gob.bo](https://geo.gob.bo/geonetwork/srv/spa/catalog.search#/home) Para shapefiles de Bolivia
```suggestion
- [geo.gob.bo](https://geo.gob.bo/geonetwork/srv/spa/catalog.search#/home) Para shapefiles de Bolivia
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +_(Recuerde que para ejecutar una linea de Comando en el Editor de RStudio Es con Ctrl+Enter o puede escribirlo directamento en la Consola)_
````suggestion
```{note}
Recuerda que para ejecutar una linea de comando en el editor de **RStudio**, se utiliza `Ctrl+Enter` o puede escribirlo directamente en la **consola**
```
````

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +Nuestra base de datos fue descargada [GeoBolivia](https://geo.gob.bo), [INE Bolivia](https://www.ine.gob.bo/) y [geodatos.net](https://www.geodatos.net/coordenadas/bolivia), una vez descargados los d
```suggestion
Nuestra base de datos fue descargada desde [GeoBolivia](https://geo.gob.bo), [INE Bolivia](https://www.ine.gob.bo/) y [geodatos.net](https://www.geodatos.net/coordenadas/bolivia), y una vez descargadas, deberán ser depuradas para sólo tener los datos de nuestro interés ([puedes descargarlos aquí]())
```

PS: falta poner el enlace a `puedes descargarlos aquí`.

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +Abrimos nuestras librerías requeridas con:
```suggestion
Abrimos nuestras librerías requeridas con:

```

PS: siempre poener una línea en blanco antes de un bloque o de una lista

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +```
````suggestion
```

````

PS: siempre poner una línea en blanco después de un bloque o de una lista

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +```python
```suggestion
```r
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +```python
```suggestion
```r
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +```python
```suggestion
```r
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +```
````suggestion
```

````

Adiciona una línea en blanco después de un bloque de código

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +```python
````suggestion

```r
````

Adiciona una línea en blanco antes del bloque de código

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +```
````suggestion
```

````

Adiciona una línea en blanco después de un bloque de código

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +- ```dsn``` directorio dentro de la carpeta donde se encuentran ficheros shapefiles, si los shapefiles estan dentro del directorio actual simplemente se pone "."
```suggestion
- `dsn`: directorio dentro de la carpeta donde se encuentran los ficheros shapefiles. Si ellos estan dentro del directorio actual simplemente se pone `"."`.
```

tripe backtick es usado para multilínea para algo inline mejor usar single backtick

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +shapefile = readOGR(dsn = ".",layer = "departamentos_geo", encoding = 'utf-8', use_iconv = TRUE)
```suggestion
shapefile = readOGR(dsn = ".", layer = "departamentos_geo", encoding = "utf-8", use_iconv = TRUE)
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +- ```encoding, use_iconv``` Indica a la función que debe leerse con la codificación "utf-8" y que si debe activarse la codificación con "TRUE". esto es necesario pues nuestro archivo importado, pues
```suggestion
- `encoding`: indica a la función que debe leerse con la codificación `utf-8`.
- `use_iconv`: esto es necesario pues nuestro archivo importado contiene caracteres con "ñ" y vocales con tíldes.
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +Para observar la estructura de nuestro shapefile importado use ```View(shapefile)```.
```suggestion
Para observar la estructura de nuestro shapefile importado, use `View(shapefile)`.
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +```
````suggestion

```r
````

Adiciona una línea en blanco antes de un bloque de código

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +```python
````suggestion

```r
````

Adiciona una línea en blanco antes de un bloque de código

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +Notesé que geotable no poseé las etiquetas de los nombres de las regiones a graficar, esto lo arreglamos con:
```suggestion

Nótese que `geotable` no poseé las etiquetas de los nombres de las regiones a graficar. Esto lo arreglamos con:
```

Adiciona una línea en blanco después de un bloque de código

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +```python
```suggestion
```r
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +#Añadiendo una columna id para poder juntar las columnas de nuestro geotable con los datos correspondientes
```suggestion
# Añadiendo una columna `id` para poder juntar las columnas de nuestro geotable con los datos correspondientes
```

- agreagar 1 espacio después de `#`
- para campos, variables, funciones y librerías dentro de textos, poner backtick ``` ` ``` para mostrar que no es un texto normal. Algunas herramientas necesitan doble backtick (por ejemplo ``` ``mylib`` ```) como por ejemplo el RST.

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +#Añadiendo a geotable los datos que faltan de shapefile, lo junta por el id
```suggestion
# Añadiendo a geotable los datos que faltan de shapefile, lo junta por el `id`
```

- agreagar 1 espacio después de `#`
- para campos, variables, funciones y librerías dentro de textos, poner backtick ``` ` ``` para mostrar que no es un texto normal. Algunas herramientas necesitan doble backtick (por ejemplo ``` ``mylib`` ```) como por ejemplo el RST.

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +```
````suggestion
```

````

Agregar línea en blanco después de un bloque de código

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +Notesé que cambiamos el nombre nuestra columna de en población DEPARTAMENTO por DEPARTAMEN para que coincidan nuestra culumnas para luego poderlas juntar con ```left_join()```.
```suggestion
Nótese que cambiamos el nombre de nuestra columna de población `DEPARTAMENTO` por `DEPARTAMEN`, así coincidarán nuestras culumnas para luego poderlas juntar con `left_join()`.
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +Ahora puede notar que se le añadió el nombre a sus respectivas coordenadas, use para ver ```head(geotable)```
```suggestion
Ahora, puedes notar que se le añadió el nombre a sus respectivas coordenadas. Usa `head(geotable)`  para visualizar los resultados.
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +Funciones auxiliares:
```suggestion
Funciones auxiliares:

```

Adiciona una línea en blanco antes de una lista

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +* ```shapefile$id <- ``` Crea una nueva columna en shapefile o la reemplaza.
```suggestion
* `shapefile$id <-`: Crea una nueva columna en el shapefile o la reemplaza.
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +* ```row.names(shapefile) ``` Extrae los nombres de las filas del shapefile que por defecto es una numeración que va desde 0 y coincide con el id de nuestro geotable.
```suggestion
* `row.names(shapefile)`: Extrae los nombres de las filas del shapefile que por defecto son numeraciones que van desde 0 y coincide con el `id`  de nuestro `geotable`.
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +* ```shapefile@data ``` Accede a la tabla o dataframe "data" de nuestro shapefile.
```suggestion
* `shapefile@data`: Accede a la tabla o dataframe `data` de nuestro shapefile.
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +* ```left_join(tabla1, tabla2, by = clave) ``` Junta dos tablas por izquierda, es decir añade valores que faltan de "tabla2" a la "tabla1" de acuerdo al código "clave" o columna común.
```suggestion
* `left_join(tabla1, tabla2, by = clave)`: Junta dos tablas por la izquierda, es decir, añade valores que faltan de `tabla2` a la `tabla1`, de acuerdo al código `clave` o columna común.
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +Ahora importamos nuestra tabla con los datos de población por departamento con(con ```header=TRUE``` nos aseguramos que la primera fila sean los nombres de las columnas):
```suggestion
Ahora, importamos nuestra tabla con los datos de población por departamento (`header=TRUE` nos asegura que en la primera fila estén los nombres de las columnas):
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +```python
```suggestion
```r
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +#Importando la tabla de datos de población
```suggestion
# Importando la tabla de datos de población
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +```
````suggestion

```
````

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +```python
````suggestion

```r
````

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +#Cambiando el nombre de la columna de DEPARTAMENTO POR DEPARTAMEN para poder juntar tablas segun nombre
```suggestion
# Cambiando el nombre de la columna de `DEPARTAMENTO` por `DEPARTAMEN`, así podemos juntar tablas según el nombre
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +#Dado que el nombre de los departamentos dentro del shapefile es DEPARTAMEN vemos conveniente cambiarlo a este.
```suggestion
# Dado que el nombre de los departamentos dentro del shapefile es `DEPARTAMEN`, vemos conveniente cambiarlo en `poblacion`.
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +#Juntamos en datos ambas tablas
```suggestion
# Juntamos en `datos` ambas tablas.
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +## Mapa con ggplot2 ⚙️
```suggestion
## Mapa con ggplot2

```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +Ahora podemos graficar :
```suggestion
Ahora, podemos graficar:
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +```python
````suggestion

```r
````

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +```
````suggestion
```

````

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +* ```geom_polygon(data, aes(x,y,group,fill))```Dibuja poligonos con la tabla "data" muestra la estetica con "aes()", x, y son los valores en ejes de las absisas y las ordenadas, estan agrupadas por e
```suggestion
* `geom_polygon(data, aes(x,y,group,fill))`: Dibuja polígonos con la tabla `data`, muestra la estética con `aes()`; `x` e `y` son los valores en ejes de las abscisas y las ordenadas; están agrupadas por el valor de la columna `group` y rellenadas con base a los valores de la columna `fill`.
```

Quizá mejor separar por `;` ya que el texto se ve como una lista de ideas y el texto no está muy fluído

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +* ```coord_equal()```Obliga a la grafica que la relación entre coordenadas sea 1:1.
```suggestion
* `coord_equal()`: Obliga a la gráfica una relación entre coordenadas de 1:1.
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/mapasenR.R
> +setwd("E:/OpenScience/mapas-article/departamentos_geo") # Redirecciona el directo actual a nuestro directorio de trabajo
parece que es el mismo código presentado en el markdown, verdad?

si es cierto, no hay necesidad de tenerlo aquí.

si quieres algo ejecutable, mejor convertir tu archivo markdown a jupyter-notebook

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +* ```lab(fill)```Pone el título a la leyenda con "fill".
```suggestion
* `lab(fill)`: Pone el título a la leyenda con `fill`.
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +## Mejorando la presentación de nuestro mapa ⚙️
```suggestion
## Mejorando la presentación de nuestro mapa

```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +Hay varias cosas que podemos modifcar para mejorar la apariencia de nuestra gráfica, como poner un título, cambiar los colores, cambiar el fondo, cambiar el formato de nuestra layenda, en esta secció
```suggestion
Hay varias cosas que podemos modifcar para mejorar la apariencia de nuestra gráfica, como poner un título, cambiar los colores, cambiar el fondo, cambiar el formato de nuestra layenda. En esta sección, mostramos como hacer esos cambios para nuestro ejemplo.
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +Inicialmente podemos extraer los valores de población y ponerlo como etiquetas dentro de nuestro mapa, para obtener sus ubicaciones dentro del mapa obtenemos un promedio de las coordenadas máximas y
```suggestion
Inicialmente, podemos extraer los valores de población y ponerlos como etiquetas dentro de nuestro mapa. Para obtener sus ubicaciones dentro del mapa, obtenemos un promedio de las coordenadas máximas y mínimas con funciones de la libería `dplyr`.
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +``` python
````suggestion

```r
````

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +Qué hicimos?
```suggestion

¿Qué hicimos?
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +* ```tabla0 %>% funcion0 %>% funcion1 ...```%>% Conocido como pipe operatortoma como argumento la "tabla0" para la "funcion0" y luego los resultados de la "funcion0" las utiliza como argumentos para
```suggestion
* `tabla0 %>% funcion0(x) %>% funcion1(x) %>% ... `: Conocido como pipe `operator`, toma como argumento la `tabla0` para la `funcion0` y luego los resultados de la `funcion0` las utiliza como argumentos para `función1` y así sucesivamente.
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +* ```group_by(col) %>% summarise(col1=accion1, col2=accion2 ...)``` Agrupa los datos en función del valor de columna "col" y con "summarise()" usa los datos agrupados para devolver nuevos valores "co
```suggestion
* `group_by(col) %>% summarise(col1=accion1, col2=accion2 ...)`: Agrupa los datos en función del valor de la columna `col`, y con `summarise()` usa los datos agrupados para devolver nuevos valores a `col1`, `col2`, etc, y pueden estar en función de los valores que estan agrupados.
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +* ```range(c)``` Extrae los valores maximo y mínimo de un rango de datos "c".
```suggestion
* `range(c)`: Extrae los valores máximo y mínimo de un rango de datos en `c`.
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +* ```mean(d)```Devuelve el valor medio del vector d.
```suggestion
* `mean(d)`: Devuelve el valor medio del vector `d`.
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +### Instalación de pre-requisitos 🔧 📋
```suggestion
### Instalación de pre-requisitos
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +## Preparación de los datos para graficar ⚙️
```suggestion
## Preparación de los datos para graficar
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +Si queremos incluir nuevas fuentes para el tipo de letra para nuestro mapa usamos los siguientes comandos(nos pedirá confirmación para realizar la importación de fuentes y tardará unos minutos en hac
```suggestion
Si queremos incluir nuevas fuentes para el tipo de letra para nuestro mapa, usamos los siguientes comandos(nos pedirá confirmación para realizar la importación de fuentes y tardará unos minutos en hacer la importación. Con el comando `fonts()`, veremos las fuentes disponiles):
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +```
````suggestion

```r
````

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +Con nuestras etiquetas podemos mejorar la visualización de datos, Usamos lo siguientes comandos para incluir las etiquetas y mejorar la apariencia.
```suggestion

Con nuestras etiquetas, podemos mejorar la visualización de datos. Usamos lo siguientes comandos para incluir las etiquetas y mejorar la apariencia de la gráfica:
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +```python
````suggestion

```r
````

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +## Referencias 📄
```suggestion
## Referencias
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +* [Instituto Nacional de Estadística Bolivia](https://www.ine.gob.bo) 📢
```suggestion
* [Instituto Nacional de Estadística Bolivia](https://www.ine.gob.bo)
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +## Autores ✒️
```suggestion
```

puedes remover la información de autor de aquí, hay qye poner esta información luego después de la imagen de portada (que estará después del título del artículo)

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +```python
````suggestion
```r
````

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +## Com guardar nuestros mapas ✒️
```suggestion
## ¿Cómo guardar nuestros mapas?

```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +## Añadiendo puntos a nuestro mapa ⚙️
```suggestion
## Añadiendo puntos a nuestro mapa
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +## Licencia 📄
puedes remover de aquí la información de licencia ... la voy a dejar en el footer general de la página
```suggestion
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +Bajo la Licencia (CC BY SA 4.0)
```suggestion
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +
```suggestion
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +
```suggestion
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +* **Ever Vino** - ** - [EverVino](https://github.com/EverVino)
```suggestion
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +
después de agregar la imagen de portada, salta una línea y agrega tu nombre:

Autor: [**EverVino**](https://github.com/EverVino)

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +```
````suggestion
```   

````

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +* ```theme_void()``` Eliminamos el fondo y los ejes de nuestra gráfica.
```suggestion
* `theme_void()`: Eliminamos el fondo y los ejes de nuestra gráfica.
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +* ```geom_text(size, alpha, fontface, data mapping=aes(x,y,label),color)``` Dibuja texto dentro del mapa sacando datos de "data" con las coordenadas "x" e"y" muestra los valores de la columna "label"
```suggestion
* `geom_text(size, alpha, fontface, data mapping=aes(x, y, label), color)`: Dibuja un texto dentro del mapa, sacando datos de `data` con las coordenadas `x` e `y`; muestra los valores de la columna `label`, las diferencia con el valor de la columna `color`. Con `size`, `alpha` y `fontface`, establecemos el tamaño, la opacidad y la estética del texto respectivamente.
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +* ```format(v, big.mark)``` Le da el formato al valor "v" de separación de miles con "big.mark" (En nuestro caso el separados de miles es sólo el espacio" ").
```suggestion
* `format(v, big.mark)`: Le da el formato al valor `v`, con separación de miles, usando `big.mark` (en nuestro caso, el separado de miles es sólo un espacio en blanco`" "`).
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +* ```labs(title, fill, caption)``` Pone el texto de los títulos, con "title", "fill", "caption" se pone el texto del título, la leyenda y el pie del gráfico respectivamente.
```suggestion
* `labs(title, fill, caption)`: Pone el texto de los títulos, con `title`, `fill` y `caption`. Se pone el texto del título, la leyenda y el pie del gráfico respectivamente.
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +* ```scale_colour_gradientn(colours,guide)``` Aplica una escala de colores a todos los valores asignados a la argumento "color" en nuestro ejemplo tenemos asignado color dentro de la función  "geom_t
```suggestion
* `scale_colour_gradientn(colours, guide)`: Aplica una escala de colores a todos los valores asignados al argumento `color`. En nuestro ejemplo, tenemos asignado un color dentro de la función  `geom_text(...aes(..color=pob...)...)`, es decir, los valores de `pob` estarán coloreados según los valores de `colours` (los parámetros `color` y `colors` puenden intercambiarse sin problema con `colour` y `colours`). `guide = "none"` evita que la leyenda de esta escala se muestre.
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +* ```scale_fill_continuous(low, high, guide, labels)``` Aplica una escala de colores continua a los valores asginados a "fill" en nuestro ejemplo tenemos asignado "fill" dentro del a función geom_pol
```suggestion
* `scale_fill_continuous(low, high, guide, labels)`: Aplica una escala de colores continua a los valores asginados a `fill`. En nuestro ejemplo, tenemos asignado `fill` dentro del a función `geom_polygon(... aes(...fill = Poblacion2022...)...)`, es decir, los valores de la columna `Poblacion2022` estarán afectados por esta función. En `low`, determinamos el color que va a tener el valor más bajo de `fill` y, con `high`, el color que va a tener el más alto valor. `guide` nos permite mostrar nuestra leyenda en forma de **colorbar**. Con `labels`, modificamos la apariencia en la escala de nuestro **colorbar**.
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +* ```scales::label_number(big.mark=" ")``` llama a la librería "scales" y aplica la función "label_number()" Con esto modificamos la apariencia de los números de nesutra leyeda poniendole un espacio
```suggestion
* `scales::label_number(big.mark=" ")`: llama a la librería `scales` y ejecuta la función `label_number()`. Con esto, modificamos la apariencia de los números de nesutra leyeda, poniendole un espacio en blanco `" "` como separador de miles. Podemos usar `scales::label_number(...)` en vez de  `library(scales); label_number()`.
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +```python
````suggestion
```r
````

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +#Importamos la localización de las ciudades capitales
```suggestion
# Importamos la localización de las ciudades capitales
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +```
````suggestion
```

````

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +* ```geom_point(alpha, data, mapping = aes(x, y, colour), size)``` Grafica puntos en el plot, con "alpha" "data", "size" modificamos la opacidad, tabla a usarse y el tamaño de los puntos, con mapping
```suggestion
* `geom_point(alpha, data, mapping = aes(x, y, colour), size)`: Grafica puntos en el plot, con `alpha`, `data`, `size` modificamos la opacidad, tabla a usarse y el tamaño de los puntos; con mapping asignamos la estética con `x`, `y` y asignamos las columnas para los valores de los ejes y con `colour`, la columna que se va a usar para asignarles colores. A este se le puede asignar un solo color también si se quiere.
```

Simplificar el texto, estás usando mucho `asignar` y sus variaciones

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +
```suggestion
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +* ```scale_fill_brewer(palette, guide)``` Es una función que aplica una escala de colores tipo brewer a todos los objetos asignados a "fill"."pallete" permite la selección de una paleta especifica y
```suggestion
* `scale_fill_brewer(palette, guide)`: Aplica una escala de colores tipo **brewer** a todos los objetos asignados a `fill`.`pallete` permite la selección de una paleta especifica y `guide` asigna la presentación de la leyenda.
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +* ```raibow(9)``` Devuelve un vector con 9 colores del arcoiris.
```suggestion
* `raibow(9)`: Devuelve un vector con los 9 colores del arcoiris.
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +![altext](grafica3.png)
```suggestion
![altext](grafica3.png)

```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +#### Como asignar los colores
```suggestion
#### ¿Cómo asignar los colores?

```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +Los colores puedes asignar simplemente usando su nombre en ingles para el blanco es "white" para el rojo "red" y así, también puedes usar su código como "#FF4500" para el rojo anaranjado. Puedes agru
```suggestion
Puedes asignar los colores simplemente usando su nombre en inglés. Para el blanco es **white**, para el rojo, **red**. También puedes usar su código hexadeciamal, como  **#FF4500** para el rojo anaranjado. Puedes agruparlos en una escala de colores, usando la función `c("red","#FF4500"...)`. Una página recomendable para seleccionar colores y obtener su código de color con un click es [r-chart.com/colors/](https://r-charts.com/colors/).
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +Los colores puedes asignar simplemente usando su nombre en ingles para el blanco es "white" para el rojo "red" y así, también puedes usar su código como "#FF4500" para el rojo anaranjado. Puedes agru
```suggestion
Puedes asignar los colores simplemente usando su nombre en inglés. Para el blanco es **white**, para el rojo, **red**. También puedes usar su código hexadeciamal, como  **#FF4500** para el rojo anaranjado. Puedes agruparlos en una escala de colores, usando la función `c("red","#FF4500"...)`. Una página recomendable para seleccionar colores y obtener su código de color con un click es [r-chart.com/colors/](https://r-charts.com/colors/).
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +Tambien puede usar la funciones auxiliares que ofrec R como scale_color/fill_brewer/viridis_ estas proporcionan escalas predefinidas que podrían mejorar el impacto visual.
```suggestion
También puede usar la funciones auxiliares que ofrece `R`, por ejemplo: `scale_color`/`fill_brewer`/`viridis_`. Estas proporcionan escalas predefinidas que podrían mejorar el impacto visual.
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +RStudio ofrece la posiblidad e exportar fácilmente desde su menú ubicado encima de la vista previa del gráfico "Export". Pero veces podemos optar por guardar nuestro mapa con mayor calidad o cierto f
```suggestion
RStudio ofrece la posiblidad e exportar fácilmente desde su menú, ubicado encima de la vista previa del gráfico "Export". Podemos optar por guardar nuestro mapa con mayor calidad o cierto formato y, para ello, podemos usar `ggsave()`, que nos permite exportar o guardar nuestro último gráfico ejecutado.
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +Guarda el mapa con el nombre "filename" en la ruta "path" con la escala y formato de "scale" y "device". COn "dpi" indicamos la cantidad de pixeles por pulgada que es la calida de nuestro archivo a e
```suggestion
Guarda el mapa con el nombre `filename` en la ruta `path`, con la escala y formato de `scale` y "device". Con `dpi`, indicamos la cantidad de pixeles por pulgada, que es la calida de nuestro archivo a exportar.
```

2022-01-29 18:03 UTC, xmnlab commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +---
```suggestion
```

2022-01-30 00:20 UTC, xmnlab commented
otros 2 puntos que se me olvidó comentar

- podrías renombrar la carpeta de 0058 a 0059?
- podrías agregar la entrada de tu artículo aquí: https://github.com/OpenScienceLabs/articles/blob/main/_toc.yml#L10


me avisas si tienes cualquier duda y avísame cuando tu PR esté listo para una nueva ronda de revisión :)

2022-01-30 14:44 UTC, EverVino commented
La hicieron las modificaciones de acuerdo a las recomendaciones. Hago otro PR

2022-01-30 14:47 UTC, EverVino commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +
Hecho

2022-01-30 14:48 UTC, EverVino commented on articles/0058-r-maps-viz/GraficaMapasR.md
> +![alt text](grafica2.png)
Hecho

2022-01-30 14:48 UTC, xmnlab commented
@EverVino no hay necesidad de hacer otro PR. Si has enviado tus actualizaciones a tu branch ya se actualiza este PR. Si tienes cualquier problema para actualizar tu branch, me avisas y te ayudo :) muchas gracias

2022-01-30 14:54 UTC, EverVino commented
Si, acabo de notar que sólo se requería solicitar una re revisión después de actualizar el branch. Gracias @xmnlab. Yo creo que todo esta en orden ahora, está lista para una nueva revisión.

2022-01-30 15:58 UTC, xmnlab reviewed
Algunos comentarios generales:

- todos los títulos/subtítulos que empiece con **Como**, **Donde**, etc que son preguntas indirectas, cambiarlas para una forma imperativa o convertirla en pregunta directas:

por ejemplo:

`Donde conseguir los archivos shapefile`

1. `¿Dónde conseguir los archivos shapefile?`

o 

2. `Conseguir los archivos shapefile`

Yo, personalmente, prefiero la opción 2

- Recomiendo la lectura de este artículo: https://www.rae.es/dpd/coma (lo vi superficialmente, parece que trata todos los casos de uso de la coma, o almenos los casos más importanes).

- Cuando hablamos con el lector, le tratamos usando tú aquí (seguimos la misma línea de [the carpentries](https://github.com/Carpentries-ES/board/blob/master/Convenciones_Traduccion.md)).

- Comentarios en R: no conozco mucho de R, pero por lo que veo aquí:

![R-styler](https://raw.githubusercontent.com/lorenzwalthert/some_raw_data/master/styler_0.1.gif)

R también pone un espacio después del `#`, por exemplo:

`#mi comentario` -> `# mi comentario`.

- Por favor, corregir todos los usos de `#` que no tenga espacio.

- Cambiar *Notesé* por *Nótese* (ref https://twitter.com/raeinforma/status/976789619005165570?lang=en)

- todas la variables, nombre de funciones o cualquier código deben de estar entre backticks ```  ` ```, aún hay unos que están entre `**`, como por ejemplo,`x`, `y`, `fill`, `data`, `id`, `tabla1`, `tabla2`, etc. Por favor, revisar todos.

2022-01-30 15:58 UTC, xmnlab commented on articles/0057-r-ggplot-bo/ArticuloGgplotenR.md
> +Hay casos en los que extrañamente no se instalan los renders para hacer la renderización de la animación y aparece un error al tratar de ejecutar el código arriba mostrado, en ese caso puede probar c
```suggestion
Hay casos en los que extrañamente no se instalan los renders para hacer la renderización de la animación y aparece un error al tratar de ejecutar el código arriba mostrado, en ese caso, puedes probar con la siguiente solución: Ejecute en modo administrador **RStudio** e instale los renders con `install.packages("gifski")` para el render que viene por defecto con `gganimate`, también puedes instalar el render magick con `install.packages("magick")` para tener otra opción para renderizar. Para saber que opciones tiene el render `magick`, ejecute `help("magick_renderer")` y se le mostrará su breve manual.
```

está un poco confusa esta parte:

```
Ejecute en modo administrador **RStudio** e instale los renders con `install.packages("gifski")` para el render que viene por defecto con `gganimate`
```

2022-01-30 15:58 UTC, xmnlab commented on articles/0057-r-ggplot-bo/ArticuloGgplotenR.md
>  Despues de ver la animación podemos guardarla haciendo:
```suggestion
Después de ver la animación, podemos guardarla haciendo:
```

2022-01-30 15:58 UTC, xmnlab commented on articles/0059-r-maps-viz/GraficaMapasR.md
> +![alt text](header.png)
alt texto no es un texto descriptivo, por favor, cambiarlo para algo que describa la imagen.

2022-01-30 15:58 UTC, xmnlab commented on articles/0059-r-maps-viz/GraficaMapasR.md
> +Adicionalmente la carpeta donde se encuentran dichos archivos pueden contener otros archivos de formato .prj o .sbn que aportan más datos de la geometría, o que pueden ser usados en otros programas d
```suggestion
Adicionalmente, la carpeta donde se encuentran dichos archivos pueden contener otros archivos de formato .prj o .sbn, estos aportan más datos de la geometría o pueden ser usados en otros programas de sistemas de información geógrafica.
```

2022-01-30 15:58 UTC, xmnlab commented on articles/0059-r-maps-viz/GraficaMapasR.md
> +Los datos importados con `rgdal` a partir de un archivo shapefile, es un objeto que contiene polígonos vectoriales con las coordenadas la latitud y la longitud en formato decimal, a partir de este ob
```suggestion
Los datos importados con `rgdal` a partir de un archivo shapefile, son objetos que contienen polígonos vectoriales con las coordenadas la latitud y la longitud en formato decimal. A partir de estos objetos, podemos extraer datos para graficarlos desde una tabla. La biblioteca `broom` nos ayuda en la extracción y logra agrupar los polígonos en diferentes grupos.
```

`agrupar ... en diferentes grupos` suena un poco redundante.

quizá podría ser: `agrupar ... por diferentes categorías`?

2022-01-30 15:58 UTC, xmnlab commented on articles/0059-r-maps-viz/GraficaMapasR.md
> +## Licencia
```suggestion
```

2022-01-30 15:58 UTC, xmnlab commented on articles/0059-r-maps-viz/GraficaMapasR.md
> +
```suggestion
```

2022-01-30 15:58 UTC, xmnlab commented on articles/0059-r-maps-viz/GraficaMapasR.md
> +Bajo la Licencia (CC BY SA 4.0)
```suggestion
```

2022-01-30 15:58 UTC, xmnlab commented on articles/0059-r-maps-viz/GraficaMapasR.md
> +Para que todas las bibliotecas funcionen correctamente se recomienda instalar o actualizar a las últimas versiones de [R](https://cran.r-project.org/) y de su IDE [RStudio](https://www.rstudio.com/)
```suggestion
Para que todas las bibliotecas funcionen correctamente, se recomienda instalar o actualizar a las últimas versiones de [R](https://cran.r-project.org/) y de su IDE [RStudio](https://www.rstudio.com/) con su correspondiente complemento [RTools](https://cran.r-project.org/bin/windows/Rtools/rtools40.html).
```

2022-01-30 15:58 UTC, xmnlab commented on articles/0059-r-maps-viz/GraficaMapasR.md
> +En este artículo vamos a utilizar archivos de formato Shapefile. Si todavía no sabes de qué se trata, te explicamos a continuación.
```suggestion
En este artículo, vamos a utilizar archivos de formato Shapefile. Si todavía no sabes de qué se trata, te explicamos a continuación.
```

2022-01-30 15:58 UTC, xmnlab commented on articles/0059-r-maps-viz/GraficaMapasR.md
> +Adicionalmente la carpeta donde se encuentran dichos archivos pueden contener otros archivos de formato .prj o .sbn que aportan más datos de la geometría, o que pueden ser usados en otros programas d
```suggestion
Adicionalmente, la carpeta donde se encuentran dichos archivos pueden contener otros archivos de formato `.prj` o `.sbn` que aportan más datos de la geometría, o que pueden ser usados en otros programas de sistemas de información geógrafico.
```

2022-01-30 15:58 UTC, xmnlab commented on articles/0059-r-maps-viz/GraficaMapasR.md
> +Muchos de estos archivos Shapefile representan mapas de nuestros Estados, por lo que están disponibles de manera gratuita en la mayoria de los casos, en otros son de paga o están más completos, actua
```suggestion
Muchos de estos archivos Shapefile representan mapas de nuestros Estados, por lo que están disponibles de manera gratuita en la mayoria de los casos, en otros, son de paga o están más completos, actualizados y/o poseen datos específicos. Debajo mostramos algunas recursos web gratuitos que puedes usar.
```

2022-01-30 15:58 UTC, xmnlab commented on articles/0059-r-maps-viz/GraficaMapasR.md
> +Nuestra base de datos fue descargada de [GeoBolivia](https://geo.gob.bo), [INE Bolivia](https://www.ine.gob.bo/) y [geodatos.net](https://www.geodatos.net/coordenadas/bolivia), una vez descargados es
```suggestion
Nuestra base de datos fue descargada de [GeoBolivia](https://geo.gob.bo), [INE Bolivia](https://www.ine.gob.bo/) y [geodatos.net](https://www.geodatos.net/coordenadas/bolivia). Una vez descargados, estos datos fueron depurados para sólo tener los datos de nuestro interés.
```

2022-01-30 15:58 UTC, xmnlab commented on articles/0059-r-maps-viz/GraficaMapasR.md
> +- **`dsn`** directorio dentro de la carpeta donde se encuentran ficheros shapefiles, si se pone sólo un punto **"."** hace referencia a que los ficheros se encuentran en el directorio actual.
poner alguna separación o poner alguna conexión (se debe usar el mismo patrón para los otros itens de la lista):

ejemplos:

- **`dsn`**: directorio ..
- **`dsn`** especifica un directorio ..
- **`dsn`**, especifica un directorio ..

PS: replicarlo para los otros itens de la lista

2022-01-30 15:58 UTC, xmnlab commented on articles/0059-r-maps-viz/GraficaMapasR.md
> +Para observar el contenido de `shapefile` use `View(shapefile)`.
```suggestion
Para observar el contenido de `shapefile`, use `View(shapefile)`.
```

2022-01-30 15:58 UTC, xmnlab commented on articles/0059-r-maps-viz/GraficaMapasR.md
> +Extrayendo datos en `geotable` para graficar y mostrando su cabecera.
```suggestion
Extrae datos en `geotable` para graficar y, en seguida, muestra su cabecera:
```

2022-01-30 15:58 UTC, xmnlab commented on articles/0059-r-maps-viz/GraficaMapasR.md
> +- **`dsn`** directorio dentro de la carpeta donde se encuentran ficheros shapefiles, si se pone sólo un punto **"."** hace referencia a que los ficheros se encuentran en el directorio actual.
```suggestion
- **`dsn`** directorio dentro de la carpeta donde se encuentran ficheros shapefiles, si se pone sólo un punto `"."` hace referencia a que los ficheros se encuentran en el directorio actual.
```

para código, siempre usarlo dentro de backticks ``` ` ```

2022-01-30 15:58 UTC, xmnlab commented on articles/0059-r-maps-viz/GraficaMapasR.md
> +- **`encoding="utf-8", use_iconv=TRUE`** indica a la función `readOGR` que debe importarse con la codificación **utf-8**. Esto es necesario para el ejemplo, pues contiene caracteres con ñ y vocales c
```suggestion
- **`encoding="utf-8", use_iconv=TRUE`** indica a la función `readOGR` que debe importarse con la codificación **utf-8**. Esto es necesario para el ejemplo, pues contiene caracteres especiales como **ñ** y vocales con tildes.
```

2022-01-30 15:58 UTC, xmnlab commented on articles/0059-r-maps-viz/GraficaMapasR.md
> +Para verificar que se han añadido los correspondientes nombres de regiones use para ver `head(geotable)`
```suggestion
Para verificar que se han añadido los correspondientes nombres de regiones, use `head(geotable)`
```

2022-01-30 15:58 UTC, xmnlab commented on articles/0059-r-maps-viz/GraficaMapasR.md
> +Funciones auxiliares:
```suggestion
Funciones auxiliares:

```

2022-01-30 15:58 UTC, xmnlab commented on articles/0059-r-maps-viz/GraficaMapasR.md
> +Ahora podemos graficar :
```suggestion
Ahora, podemos graficar:
```

2022-01-30 15:58 UTC, xmnlab commented on articles/0059-r-maps-viz/GraficaMapasR.md
> +* **`geom_polygon(data, aes(x, y, group, fill))`** dibuja polígonos con la tabla **data** muestra la estética con **aes()**.
```suggestion
* **`geom_polygon(data, aes(x, y, group, fill))`** dibuja polígonos con la tabla **data** y muestra la estética con **aes()**.
```

2022-01-30 16:04 UTC, xmnlab commented
@EverVino agregué más comentarios, pero no agregué todos los comentarios línea por línea (algunos sí).
por favor, hacer una revisión general usando los lineamientos descritos aquí https://github.com/OpenScienceLabs/articles/pull/4#pullrequestreview-867123059

otra cosa, vi que has cambiado tu artículo anterior en este PR. Para las próximas, es mejor que no cambies un artículo en un PR que está agregando un nuevo artículo. Como buena práctica, es bueno que un PR resuelva un tema específico.

avísame si tienes cualquier duda. y avísame cuando esté listo para una nueva revisión.
muchas gracias!

2022-01-30 19:17 UTC, EverVino commented on articles/0057-r-ggplot-bo/ArticuloGgplotenR.md
> +Hay casos en los que extrañamente no se instalan los renders para hacer la renderización de la animación y aparece un error al tratar de ejecutar el código arriba mostrado, en ese caso puede probar c
Esto corresponde a otro PR, para arreglar en anterior artículo

2022-01-30 19:17 UTC, EverVino commented on articles/0059-r-maps-viz/GraficaMapasR.md
> +![alt text](header.png)
Hecho

2022-01-30 19:19 UTC, EverVino commented
Se se hicieron las corecciones espero no se me haya pasado nada. listo para una nueva revisión @xmnlab

2022-02-03 15:40 UTC, xmnlab commented
@EverVino , estoy un poco liado aquí con el tema de la estructura de la página de los artículos.
creo que lo voy a revisarlo este fin de semana.
en este tiempo, podrías actualizar tu branch con el main de upstream (https://github.com/OpenScienceLabs/articles)? 2 archivos tienen conflicto.

2022-02-03 17:29 UTC, xmnlab commented on _toc.yml
> +=======
algún motivo para adicionar esta línea?
no es parte de la estructura de un yaml file.
adicionalmente, esta línea está saltando un error en el CI: https://github.com/OpenScienceLabs/articles/runs/5055604658?check_suite_focus=true#step:5:62

2022-02-03 17:34 UTC, EverVino commented on _toc.yml
> +=======
Mientras estaba corrigiendo esa línea se quedo pero ya la eliminé. Ya no salta el error.

2022-02-03 17:38 UTC, xmnlab commented on _toc.yml
> +=======
entiendo. probablemente eso era de la sintaxis de git para mostrar los conflictos. muchas gracias!

2022-02-07 02:36 UTC, xmnlab commented
superseded by #9

2022-02-07 02:36 UTC, closed without merging